<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160408111438 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE counter CHANGE page page VARCHAR(200) NOT NULL, CHANGE hit hit INT NOT NULL');
        $this->addSql('ALTER TABLE tbl_agenda CHANGE sottotitolo sottotitolo VARCHAR(200) DEFAULT NULL, CHANGE link link VARCHAR(200) NOT NULL');
        $this->addSql('ALTER TABLE tbl_aree CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_aree id_tbl_aree INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(50) DEFAULT NULL, CHANGE id_tbl_menu id_tbl_menu INT DEFAULT NULL, CHANGE accesskey accesskey VARCHAR(2) DEFAULT NULL, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(200) DEFAULT NULL, CHANGE checkbox_tbl_service checkbox_tbl_service VARCHAR(200) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE img img VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_cat_agenda CHANGE icona icona VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_cat_link CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_cat_link id_tbl_cat_link INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE nome nome VARCHAR(100) NOT NULL, CHANGE smarty_template smarty_template VARCHAR(200) NOT NULL, CHANGE posizione posizione INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_cat_modelli CHANGE nome nome VARCHAR(80) NOT NULL');
        $this->addSql('ALTER TABLE tbl_comunicatistampa CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_comunicatistampa id_tbl_comunicatistampa INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE pub pub TINYINT(1) DEFAULT NULL, CHANGE data_inizio_pub data_inizio_pub DATE NOT NULL, CHANGE data_comunicato data_comunicato DATE DEFAULT NULL, CHANGE id_tbl_comunicatistampa_cat id_tbl_comunicatistampa_cat INT DEFAULT NULL, CHANGE in_preview in_preview TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_comunicatistampa_cat CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_comunicatistampa_cat id_tbl_comunicatistampa_cat INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(50) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE n_days n_days SMALLINT DEFAULT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) DEFAULT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT DEFAULT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT DEFAULT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_comunicatistampa_setup CHANGE id id TINYINT(1) NOT NULL, CHANGE id_tbl_comunicatistampa_setup id_tbl_comunicatistampa_setup TINYINT(1) DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua TINYINT(1) NOT NULL, CHANGE n_days n_days SMALLINT NOT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) NOT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT NOT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT NOT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT NOT NULL, CHANGE max_n_page max_n_page SMALLINT NOT NULL, CHANGE template_list_preview template_list_preview VARCHAR(255) NOT NULL, CHANGE template_list template_list VARCHAR(255) NOT NULL, CHANGE template template VARCHAR(255) NOT NULL, CHANGE template_search template_search VARCHAR(255) NOT NULL, CHANGE setlocale setlocale VARCHAR(255) NOT NULL, CHANGE format_date_list format_date_list VARCHAR(255) NOT NULL, CHANGE format_date_page format_date_page VARCHAR(255) NOT NULL, CHANGE format_date_preview format_date_preview VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tbl_datimoduli CHANGE id_session id_session VARCHAR(50) NOT NULL, CHANGE last_ping last_ping INT NOT NULL, CHANGE id_tbl_form id_tbl_form INT NOT NULL');
        $this->addSql('ALTER TABLE tbl_doc CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc id_tbl_doc INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE id_tbl_doc_cat id_tbl_doc_cat INT NOT NULL, CHANGE filesource filesource VARCHAR(255) NOT NULL, CHANGE mimetype mimetype LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE save_as_zip save_as_zip TINYINT(1) NOT NULL, CHANGE filesize filesize INT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE num_times_downloaded num_times_downloaded BIGINT DEFAULT NULL, CHANGE pub pub TINYINT(1) NOT NULL, CHANGE pos pos INT NOT NULL, CHANGE tag_associated tag_associated VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tbl_doc_cat CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc_cat id_tbl_doc_cat INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE title title VARCHAR(50) DEFAULT NULL, CHANGE pos pos INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_doc_classificator CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE id_tbl_doc id_tbl_doc INT NOT NULL, CHANGE id_tbl_doc_properties id_tbl_doc_properties INT NOT NULL, CHANGE property_value_reference property_value_reference INT NOT NULL');
        $this->addSql('ALTER TABLE tbl_doc_properties CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc_properties id_tbl_doc_properties INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE property property VARCHAR(255) NOT NULL, CHANGE type_property type_property LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE compulsory compulsory TINYINT(1) NOT NULL, CHANGE id_padre id_padre INT DEFAULT NULL, CHANGE type_use type_use LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE pos pos INT DEFAULT NULL, CHANGE admin_type_order admin_type_order LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE visible visible INT NOT NULL, CHANGE compulsory_web compulsory_web INT DEFAULT NULL, CHANGE tag_associated tag_associated VARCHAR(255) NOT NULL, CHANGE web_type_order web_type_order LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE tbl_doc_property_values CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc_property_values id_tbl_doc_property_values INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE id_tbl_doc_properties id_tbl_doc_properties INT NOT NULL, CHANGE property_value property_value VARCHAR(255) NOT NULL, CHANGE id_padre id_padre INT DEFAULT NULL, CHANGE pos pos INT NOT NULL, CHANGE id_tbl_menu id_tbl_menu INT DEFAULT NULL, CHANGE tag_associated tag_associated VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tbl_form CHANGE nome nome VARCHAR(50) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_gestore_risorse CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE id_utente id_utente INT NOT NULL, CHANGE start_time start_time DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tbl_gruppi CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(50) NOT NULL, CHANGE descr descr VARCHAR(70) NOT NULL');
        $this->addSql('ALTER TABLE tbl_history_admin CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE type_action type_action LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE tbl_input CHANGE nome nome VARCHAR(100) DEFAULT NULL, CHANGE tipo tipo VARCHAR(50) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE `label` `label` VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_lingua CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE img img VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_link CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_link id_tbl_link INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE nome nome VARCHAR(50) NOT NULL, CHANGE link link VARCHAR(150) NOT NULL, CHANGE img img VARCHAR(150) DEFAULT NULL, CHANGE id_tbl_cat_link id_tbl_cat_link INT NOT NULL, CHANGE id_tbl_target id_tbl_target INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_menu CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(100) DEFAULT NULL, CHANGE id_tbl_menu id_tbl_menu INT DEFAULT NULL, CHANGE pub pub TINYINT(1) DEFAULT NULL, CHANGE id_padre id_padre INT DEFAULT NULL, CHANGE checkbox_intention checkbox_intention VARCHAR(100) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(200) DEFAULT NULL, CHANGE checkbox_tbl_service checkbox_tbl_service VARCHAR(200) DEFAULT NULL, CHANGE img img VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_messaggi CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_messaggi id_tbl_messaggi INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE oggetto oggetto VARCHAR(80) DEFAULT NULL, CHANGE Stato Stato INT NOT NULL, CHANGE id_tbl_page id_tbl_page INT NOT NULL, CHANGE datamod datamod DATE NOT NULL');
        $this->addSql('ALTER TABLE tbl_modelli CHANGE nome nome VARCHAR(50) DEFAULT NULL, CHANGE id_tbl_cat_modelli id_tbl_cat_modelli INT DEFAULT NULL, CHANGE img img VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_notizie CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_notizie id_tbl_notizie INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE titolo titolo VARCHAR(255) NOT NULL, CHANGE sottotitolo sottotitolo VARCHAR(255) NOT NULL, CHANGE pub pub TINYINT(1) DEFAULT NULL, CHANGE id_tbl_notizie_cat id_tbl_notizie_cat INT DEFAULT NULL, CHANGE in_preview in_preview TINYINT(1) DEFAULT NULL, CHANGE have_agenda have_agenda TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE tbl_notizie_cat CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_notizie_cat id_tbl_notizie_cat INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(100) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) DEFAULT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT DEFAULT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT DEFAULT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_notizie_setup CHANGE id id TINYINT(1) NOT NULL, CHANGE id_tbl_notizie_setup id_tbl_notizie_setup TINYINT(1) DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua TINYINT(1) NOT NULL, CHANGE n_days n_days SMALLINT NOT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) NOT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT NOT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT NOT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT NOT NULL, CHANGE max_n_page max_n_page SMALLINT NOT NULL, CHANGE template_list_preview template_list_preview VARCHAR(255) NOT NULL, CHANGE template_list template_list VARCHAR(255) NOT NULL, CHANGE template template VARCHAR(255) NOT NULL, CHANGE template_search template_search VARCHAR(255) NOT NULL, CHANGE setlocale setlocale VARCHAR(255) NOT NULL, CHANGE format_date_list format_date_list VARCHAR(255) NOT NULL, CHANGE format_date_page format_date_page VARCHAR(255) NOT NULL, CHANGE format_date_preview format_date_preview VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tbl_page ADD custom_field INT DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_page id_tbl_page INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(255) DEFAULT NULL, CHANGE id_tbl_menu id_tbl_menu INT DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(255) DEFAULT NULL, CHANGE checkbox_tbl_service checkbox_tbl_service VARCHAR(255) DEFAULT NULL, CHANGE id_tbl_tipo_pagina id_tbl_tipo_pagina INT DEFAULT NULL, CHANGE id_tbl_photo id_tbl_photo INT DEFAULT NULL, CHANGE utentemod utentemod VARCHAR(100) DEFAULT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT DEFAULT NULL, CHANGE pub pub INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_page_classificator CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE id_tbl_page id_tbl_page INT NOT NULL, CHANGE id_tbl_page_properties id_tbl_page_properties INT NOT NULL, CHANGE property_value_reference property_value_reference INT NOT NULL');
        $this->addSql('ALTER TABLE tbl_page_properties CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_page_properties id_tbl_page_properties INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE type_property type_property LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE compulsory compulsory TINYINT(1) NOT NULL, CHANGE id_padre id_padre INT DEFAULT NULL, CHANGE pos pos INT DEFAULT NULL, CHANGE admin_type_order admin_type_order LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE visible visible INT NOT NULL, CHANGE compulsory_web compulsory_web INT DEFAULT NULL, CHANGE web_type_order web_type_order LONGTEXT NOT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE tbl_page_property_values CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_page_property_values id_tbl_page_property_values INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE id_tbl_page_properties id_tbl_page_properties INT NOT NULL, CHANGE id_padre id_padre INT DEFAULT NULL, CHANGE pos pos INT NOT NULL, CHANGE id_tbl_menu id_tbl_menu INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_photo CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_tbl_photo id_tbl_photo INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(100) DEFAULT NULL, CHANGE img img VARCHAR(255) DEFAULT NULL, CHANGE img_big img_big VARCHAR(255) DEFAULT NULL, CHANGE thumbnail_x thumbnail_x INT DEFAULT NULL, CHANGE thumbnail_y thumbnail_y INT DEFAULT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE pub pub INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_photo_cat CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE id_padre id_padre INT DEFAULT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT DEFAULT NULL, CHANGE nome nome VARCHAR(50) DEFAULT NULL, CHANGE num num INT DEFAULT NULL, CHANGE smarty_template smarty_template VARCHAR(200) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL, CHANGE set_loop set_loop TINYINT(1) DEFAULT NULL, CHANGE set_random set_random TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_photo_import CHANGE id id TINYINT(1) NOT NULL, CHANGE id_tbl_photo_import id_tbl_photo_import INT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT NOT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT DEFAULT NULL, CHANGE id_tbl_photo_cat_added id_tbl_photo_cat_added INT DEFAULT NULL, CHANGE quality quality TINYINT(1) NOT NULL, CHANGE dimx dimx INT DEFAULT NULL, CHANGE dimy dimy INT DEFAULT NULL, CHANGE thumbnail_dimx thumbnail_dimx INT DEFAULT NULL, CHANGE thumbnail_dimy thumbnail_dimy INT DEFAULT NULL, CHANGE watermark_textsize watermark_textsize TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_phpmailer_log CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE id_user id_user INT DEFAULT NULL, CHANGE mail_date mail_date DATETIME NOT NULL');
        $this->addSql('ALTER TABLE tbl_pratiche CHANGE id id TINYINT(1) NOT NULL, CHANGE pratica pratica INT DEFAULT NULL, CHANGE id_tbl_img_stato_pratiche id_tbl_img_stato_pratiche INT NOT NULL, CHANGE id_tbl_tipo_mutuo id_tbl_tipo_mutuo INT NOT NULL');
        $this->addSql('ALTER TABLE tbl_qtool CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT NULL, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(150) DEFAULT NULL, CHANGE posizione posizione INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_service CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(50) DEFAULT NULL, CHANGE descr descr VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_target CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE tbl_tipo_pagina CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('DROP INDEX id_2 ON tbl_traduzioni');
        $this->addSql('ALTER TABLE tbl_traduzioni CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE tbl_user CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT NULL, CHANGE cognome cognome VARCHAR(30) DEFAULT NULL, CHANGE email email VARCHAR(50) DEFAULT NULL, CHANGE login login VARCHAR(20) NOT NULL, CHANGE password password VARCHAR(50) NOT NULL, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(200) DEFAULT NULL, CHANGE checkbox1_tbl_gruppi checkbox1_tbl_gruppi VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_user_service CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT NULL, CHANGE cognome cognome VARCHAR(30) DEFAULT NULL, CHANGE email email VARCHAR(50) DEFAULT NULL, CHANGE login login VARCHAR(50) NOT NULL, CHANGE accetta_privacy accetta_privacy TINYINT(1) NOT NULL, CHANGE accetta_newsletter accetta_newsletter TINYINT(1) NOT NULL, CHANGE pub pub TINYINT(1) NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua TINYINT(1) NOT NULL, CHANGE downloaded downloaded TINYINT(1) NOT NULL, CHANGE del del TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE useronline CHANGE zeit zeit INT NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE counter CHANGE page page VARCHAR(200) DEFAULT \'0\' NOT NULL COLLATE utf8_general_ci, CHANGE hit hit INT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE tbl_agenda CHANGE sottotitolo sottotitolo VARCHAR(200) DEFAULT \'sottotitolo\' COLLATE utf8_general_ci, CHANGE link link VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_aree CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_aree id_tbl_aree INT DEFAULT 0 NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE nome nome VARCHAR(50) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE id_tbl_menu id_tbl_menu INT UNSIGNED DEFAULT 1, CHANGE accesskey accesskey CHAR(2) DEFAULT NULL COLLATE utf8_general_ci, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(200) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE checkbox_tbl_service checkbox_tbl_service VARCHAR(200) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE posizione posizione INT DEFAULT 0, CHANGE img img VARCHAR(100) DEFAULT \'.gif\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_cat_agenda CHANGE icona icona VARCHAR(80) DEFAULT \'.gif\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_cat_link CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_cat_link id_tbl_cat_link INT UNSIGNED NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE nome nome VARCHAR(100) DEFAULT \'nome categoria\' NOT NULL COLLATE utf8_general_ci, CHANGE smarty_template smarty_template VARCHAR(200) DEFAULT \'link.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE posizione posizione INT UNSIGNED DEFAULT 11');
        $this->addSql('ALTER TABLE tbl_cat_modelli CHANGE nome nome VARCHAR(80) DEFAULT \'nome categoria modello di pagina\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_comunicatistampa CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_comunicatistampa id_tbl_comunicatistampa INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE pub pub TINYINT(1) DEFAULT NULL, CHANGE data_inizio_pub data_inizio_pub DATE DEFAULT \'0000-00-00\' NOT NULL, CHANGE data_comunicato data_comunicato DATE DEFAULT \'0000-00-00\', CHANGE id_tbl_comunicatistampa_cat id_tbl_comunicatistampa_cat INT UNSIGNED DEFAULT 0, CHANGE in_preview in_preview TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_comunicatistampa_cat CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_comunicatistampa_cat id_tbl_comunicatistampa_cat INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE nome nome VARCHAR(50) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE posizione posizione INT UNSIGNED DEFAULT 11, CHANGE n_days n_days SMALLINT UNSIGNED DEFAULT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) DEFAULT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT UNSIGNED DEFAULT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT UNSIGNED DEFAULT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_comunicatistampa_setup CHANGE id id TINYINT(1) NOT NULL, CHANGE id_tbl_comunicatistampa_setup id_tbl_comunicatistampa_setup TINYINT(1) DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua TINYINT(1) DEFAULT \'4\' NOT NULL, CHANGE n_days n_days SMALLINT UNSIGNED DEFAULT 30 NOT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) DEFAULT \'5\' NOT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE max_n_page max_n_page SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE template_list_preview template_list_preview VARCHAR(255) DEFAULT \'comunicatistampa_preview.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE template_list template_list VARCHAR(255) DEFAULT \'comunicatistampa_paginato.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE template template VARCHAR(255) DEFAULT \'comunicato.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE template_search template_search VARCHAR(255) DEFAULT \'comunicatistampa_ricerca.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE setlocale setlocale VARCHAR(255) DEFAULT \'it_IT\' NOT NULL COLLATE utf8_general_ci, CHANGE format_date_list format_date_list VARCHAR(255) DEFAULT \'%d %B %Y\' NOT NULL COLLATE utf8_general_ci, CHANGE format_date_page format_date_page VARCHAR(255) DEFAULT \'%d %B %Y\' NOT NULL COLLATE utf8_general_ci, CHANGE format_date_preview format_date_preview VARCHAR(255) DEFAULT \'%d %B %Y\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_datimoduli CHANGE id_session id_session VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE last_ping last_ping INT DEFAULT 0 NOT NULL, CHANGE id_tbl_form id_tbl_form INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE tbl_doc CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc id_tbl_doc INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE id_tbl_doc_cat id_tbl_doc_cat INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE filesource filesource VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE mimetype mimetype LONGTEXT DEFAULT \'xxx\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\', CHANGE save_as_zip save_as_zip TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE filesize filesize INT UNSIGNED DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE num_times_downloaded num_times_downloaded BIGINT UNSIGNED DEFAULT NULL, CHANGE pub pub TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE pos pos INT DEFAULT 1 NOT NULL, CHANGE tag_associated tag_associated VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_doc_cat CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc_cat id_tbl_doc_cat INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE title title VARCHAR(50) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE pos pos INT UNSIGNED DEFAULT 11');
        $this->addSql('ALTER TABLE tbl_doc_classificator CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE id_tbl_doc id_tbl_doc INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE id_tbl_doc_properties id_tbl_doc_properties INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE property_value_reference property_value_reference INT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE tbl_doc_properties CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc_properties id_tbl_doc_properties INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE property property VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE type_property type_property LONGTEXT DEFAULT \'insieme di valori a selezione singola\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\', CHANGE compulsory compulsory TINYINT(1) DEFAULT \'1\' NOT NULL, CHANGE id_padre id_padre INT UNSIGNED DEFAULT NULL, CHANGE type_use type_use LONGTEXT DEFAULT \'\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\', CHANGE pos pos INT UNSIGNED DEFAULT NULL, CHANGE admin_type_order admin_type_order LONGTEXT DEFAULT \'per posizione\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\', CHANGE visible visible INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE compulsory_web compulsory_web INT UNSIGNED DEFAULT NULL, CHANGE tag_associated tag_associated VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE web_type_order web_type_order LONGTEXT DEFAULT \'per posizione\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE tbl_doc_property_values CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_doc_property_values id_tbl_doc_property_values INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE id_tbl_doc_properties id_tbl_doc_properties INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE property_value property_value VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE id_padre id_padre INT UNSIGNED DEFAULT NULL, CHANGE pos pos INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE id_tbl_menu id_tbl_menu INT UNSIGNED DEFAULT NULL, CHANGE tag_associated tag_associated VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_form CHANGE nome nome VARCHAR(50) DEFAULT \'nome form\' COLLATE utf8_general_ci, CHANGE posizione posizione INT DEFAULT 1');
        $this->addSql('ALTER TABLE tbl_gestore_risorse CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_utente id_utente INT UNSIGNED NOT NULL, CHANGE start_time start_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE tbl_gruppi CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(50) DEFAULT \'nome\' NOT NULL COLLATE utf8_general_ci, CHANGE descr descr VARCHAR(70) DEFAULT \'desc\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_history_admin CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE type_action type_action LONGTEXT DEFAULT \'edit\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE tbl_input CHANGE nome nome VARCHAR(100) DEFAULT \'nome input\' COLLATE utf8_general_ci, CHANGE tipo tipo VARCHAR(50) DEFAULT \'tipo input\' COLLATE utf8_general_ci, CHANGE posizione posizione INT DEFAULT 1, CHANGE `label` `label` VARCHAR(100) DEFAULT \'label input\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_lingua CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE img img VARCHAR(100) DEFAULT \'.gif\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_link CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_link id_tbl_link INT UNSIGNED NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE nome nome VARCHAR(50) DEFAULT \'nome link\' NOT NULL COLLATE utf8_general_ci, CHANGE link link VARCHAR(150) DEFAULT \'http://\' NOT NULL COLLATE utf8_general_ci, CHANGE img img VARCHAR(150) DEFAULT \'.gif\' COLLATE utf8_general_ci, CHANGE id_tbl_cat_link id_tbl_cat_link INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE id_tbl_target id_tbl_target INT UNSIGNED DEFAULT 0');
        $this->addSql('ALTER TABLE tbl_menu CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 2, CHANGE nome nome VARCHAR(100) DEFAULT \'nome\' COLLATE utf8_general_ci, CHANGE id_tbl_menu id_tbl_menu INT UNSIGNED DEFAULT 0, CHANGE pub pub TINYINT(1) DEFAULT \'1\', CHANGE id_padre id_padre INT UNSIGNED DEFAULT 0, CHANGE checkbox_intention checkbox_intention VARCHAR(100) DEFAULT \'1,2,3,4,5,6\' COLLATE utf8_general_ci, CHANGE posizione posizione INT DEFAULT 0, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(200) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE checkbox_tbl_service checkbox_tbl_service VARCHAR(200) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE img img VARCHAR(100) DEFAULT \'.gif\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_messaggi CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_messaggi id_tbl_messaggi INT UNSIGNED NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE oggetto oggetto VARCHAR(80) DEFAULT \'oggetto della mail\' COLLATE utf8_general_ci, CHANGE Stato Stato INT DEFAULT 0 NOT NULL, CHANGE id_tbl_page id_tbl_page INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE datamod datamod DATE DEFAULT \'0000-00-00\' NOT NULL');
        $this->addSql('ALTER TABLE tbl_modelli CHANGE nome nome VARCHAR(50) DEFAULT \'nome modello di pagina\' COLLATE utf8_general_ci, CHANGE id_tbl_cat_modelli id_tbl_cat_modelli INT DEFAULT 1, CHANGE img img VARCHAR(100) DEFAULT \'.gif\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_notizie CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_notizie id_tbl_notizie INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE titolo titolo VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE sottotitolo sottotitolo VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, CHANGE pub pub TINYINT(1) DEFAULT NULL, CHANGE id_tbl_notizie_cat id_tbl_notizie_cat INT UNSIGNED DEFAULT NULL, CHANGE in_preview in_preview TINYINT(1) DEFAULT NULL, CHANGE have_agenda have_agenda TINYINT(1) DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE tbl_notizie_cat CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_notizie_cat id_tbl_notizie_cat INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE nome nome VARCHAR(100) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE posizione posizione INT UNSIGNED DEFAULT 11, CHANGE n_visible_preview n_visible_preview TINYINT(1) DEFAULT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT UNSIGNED DEFAULT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT UNSIGNED DEFAULT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_notizie_setup CHANGE id id TINYINT(1) NOT NULL, CHANGE id_tbl_notizie_setup id_tbl_notizie_setup TINYINT(1) DEFAULT NULL, CHANGE id_tbl_lingua id_tbl_lingua TINYINT(1) DEFAULT \'4\' NOT NULL, CHANGE n_days n_days SMALLINT UNSIGNED DEFAULT 30 NOT NULL, CHANGE n_visible_preview n_visible_preview TINYINT(1) DEFAULT \'5\' NOT NULL, CHANGE n_item_x_page_active n_item_x_page_active SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE n_item_x_page_archive n_item_x_page_archive SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE n_item_x_page_search n_item_x_page_search SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE max_n_page max_n_page SMALLINT UNSIGNED DEFAULT 10 NOT NULL, CHANGE template_list_preview template_list_preview VARCHAR(255) DEFAULT \'notizie_preview.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE template_list template_list VARCHAR(255) DEFAULT \'notizie_paginato.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE template template VARCHAR(255) DEFAULT \'notizie.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE template_search template_search VARCHAR(255) DEFAULT \'notizie_ricerca.tpl\' NOT NULL COLLATE utf8_general_ci, CHANGE setlocale setlocale VARCHAR(255) DEFAULT \'it_IT\' NOT NULL COLLATE utf8_general_ci, CHANGE format_date_list format_date_list VARCHAR(255) DEFAULT \'%d %B %Y\' NOT NULL COLLATE utf8_general_ci, CHANGE format_date_page format_date_page VARCHAR(255) DEFAULT \'%d %B %Y\' NOT NULL COLLATE utf8_general_ci, CHANGE format_date_preview format_date_preview VARCHAR(255) DEFAULT \'%d %B %Y\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_page DROP custom_field, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_page id_tbl_page INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE nome nome VARCHAR(255) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE id_tbl_menu id_tbl_menu INT UNSIGNED DEFAULT 1, CHANGE posizione posizione INT UNSIGNED DEFAULT 0, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(255) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE checkbox_tbl_service checkbox_tbl_service VARCHAR(255) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE id_tbl_tipo_pagina id_tbl_tipo_pagina INT DEFAULT 1, CHANGE id_tbl_photo id_tbl_photo INT DEFAULT 0, CHANGE utentemod utentemod VARCHAR(100) DEFAULT \'pippo (182.1.1.1)\' COLLATE utf8_general_ci, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT DEFAULT 1, CHANGE pub pub INT DEFAULT 1');
        $this->addSql('ALTER TABLE tbl_page_classificator CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE id_tbl_page id_tbl_page INT UNSIGNED NOT NULL, CHANGE id_tbl_page_properties id_tbl_page_properties INT UNSIGNED NOT NULL, CHANGE property_value_reference property_value_reference INT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE tbl_page_properties CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_page_properties id_tbl_page_properties INT UNSIGNED NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE type_property type_property LONGTEXT DEFAULT \'insieme di valori a selezione singola\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\', CHANGE compulsory compulsory TINYINT(1) DEFAULT \'1\' NOT NULL, CHANGE id_padre id_padre INT UNSIGNED DEFAULT NULL, CHANGE pos pos INT UNSIGNED DEFAULT NULL, CHANGE admin_type_order admin_type_order LONGTEXT DEFAULT \'per posizione\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\', CHANGE visible visible INT UNSIGNED NOT NULL, CHANGE compulsory_web compulsory_web INT UNSIGNED DEFAULT NULL, CHANGE web_type_order web_type_order LONGTEXT DEFAULT \'per posizione\' NOT NULL COLLATE utf8_general_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE tbl_page_property_values CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_page_property_values id_tbl_page_property_values INT UNSIGNED NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4 NOT NULL, CHANGE id_tbl_page_properties id_tbl_page_properties INT UNSIGNED NOT NULL, CHANGE id_padre id_padre INT UNSIGNED DEFAULT NULL, CHANGE pos pos INT UNSIGNED NOT NULL, CHANGE id_tbl_menu id_tbl_menu INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_photo CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_tbl_photo id_tbl_photo INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE nome nome VARCHAR(100) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE img img VARCHAR(255) DEFAULT \'.gif\' COLLATE utf8_general_ci, CHANGE img_big img_big VARCHAR(255) DEFAULT \'.gif\' COLLATE utf8_general_ci, CHANGE thumbnail_x thumbnail_x INT UNSIGNED DEFAULT NULL, CHANGE thumbnail_y thumbnail_y INT UNSIGNED DEFAULT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT UNSIGNED DEFAULT 0, CHANGE posizione posizione INT UNSIGNED DEFAULT 10, CHANGE pub pub INT DEFAULT 1');
        $this->addSql('ALTER TABLE tbl_photo_cat CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_padre id_padre INT UNSIGNED DEFAULT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT DEFAULT 0, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED DEFAULT 4, CHANGE nome nome VARCHAR(50) DEFAULT \'nome tradotto\' COLLATE utf8_general_ci, CHANGE num num INT UNSIGNED DEFAULT 5, CHANGE smarty_template smarty_template VARCHAR(200) DEFAULT \'album.tpl\' COLLATE utf8_general_ci, CHANGE posizione posizione INT DEFAULT 0, CHANGE set_loop set_loop TINYINT(1) DEFAULT NULL, CHANGE set_random set_random TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_photo_import CHANGE id id TINYINT(1) NOT NULL, CHANGE id_tbl_photo_import id_tbl_photo_import INT UNSIGNED NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua INT UNSIGNED NOT NULL, CHANGE id_tbl_photo_cat id_tbl_photo_cat INT UNSIGNED DEFAULT NULL, CHANGE id_tbl_photo_cat_added id_tbl_photo_cat_added INT UNSIGNED DEFAULT NULL, CHANGE quality quality TINYINT(1) NOT NULL, CHANGE dimx dimx INT UNSIGNED DEFAULT NULL, CHANGE dimy dimy INT UNSIGNED DEFAULT NULL, CHANGE thumbnail_dimx thumbnail_dimx INT UNSIGNED DEFAULT NULL, CHANGE thumbnail_dimy thumbnail_dimy INT UNSIGNED DEFAULT NULL, CHANGE watermark_textsize watermark_textsize TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE tbl_phpmailer_log CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE id_user id_user INT UNSIGNED DEFAULT NULL, CHANGE mail_date mail_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE tbl_pratiche CHANGE id id TINYINT(1) NOT NULL, CHANGE pratica pratica INT UNSIGNED DEFAULT NULL, CHANGE id_tbl_img_stato_pratiche id_tbl_img_stato_pratiche INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE id_tbl_tipo_mutuo id_tbl_tipo_mutuo INT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE tbl_qtool CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT \'nome\' COLLATE utf8_general_ci, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(150) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE posizione posizione INT UNSIGNED DEFAULT 10');
        $this->addSql('ALTER TABLE tbl_service CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(50) DEFAULT \'nome\' COLLATE utf8_general_ci, CHANGE descr descr VARCHAR(80) DEFAULT \'descrizione servizio\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_target CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT \'_self\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_tipo_pagina CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE tbl_traduzioni CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE INDEX id_2 ON tbl_traduzioni (id)');
        $this->addSql('ALTER TABLE tbl_user CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT \'nome\' COLLATE utf8_general_ci, CHANGE cognome cognome VARCHAR(30) DEFAULT \'cognome\' COLLATE utf8_general_ci, CHANGE email email VARCHAR(50) DEFAULT \'email\' COLLATE utf8_general_ci, CHANGE login login VARCHAR(20) DEFAULT \'login\' NOT NULL COLLATE utf8_general_ci, CHANGE password password VARCHAR(50) DEFAULT \'passw\' NOT NULL COLLATE utf8_general_ci, CHANGE checkbox_tbl_gruppi checkbox_tbl_gruppi VARCHAR(200) DEFAULT \',,\' COLLATE utf8_general_ci, CHANGE checkbox1_tbl_gruppi checkbox1_tbl_gruppi VARCHAR(200) DEFAULT \',,\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE tbl_user_service CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nome nome VARCHAR(30) DEFAULT \'nome\' COLLATE utf8_general_ci, CHANGE cognome cognome VARCHAR(30) DEFAULT \'cognome\' COLLATE utf8_general_ci, CHANGE email email VARCHAR(50) DEFAULT \'email\' COLLATE utf8_general_ci, CHANGE login login VARCHAR(50) DEFAULT \'login\' NOT NULL COLLATE utf8_general_ci, CHANGE accetta_privacy accetta_privacy TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE accetta_newsletter accetta_newsletter TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE pub pub TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE id_tbl_lingua id_tbl_lingua TINYINT(1) DEFAULT \'4\' NOT NULL, CHANGE downloaded downloaded TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE del del TINYINT(1) DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE useronline CHANGE zeit zeit INT DEFAULT 0 NOT NULL');
    }
}
